'use strict';
const {calculate,definitions}=MiFlowMetrics;
const patients=MIFLOW_DATA.patients;
let selected=0,tab='overview',group='All',query='',timelineMode='All';
const $=s=>document.querySelector(s);
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const def=k=>definitions.find(x=>x.key===k);
function fmt(v,key){if(v===null||v===undefined)return '—';if(typeof v==='string')return v;
 const decimals=['ni','sleepHours','firstSleep','duration','flowSurrogate','conductance'].includes(key)?2:['npi','peakFullness','efficiency','fatTrend','fat','fillingRate','urgeFullness','meanVoid','heartRate'].includes(key)?1:0;
 return v.toLocaleString('en-US',{maximumFractionDigits:decimals,minimumFractionDigits:0});}
function clock(minute){const t=(minute+360)%1440;return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`;}
function patientPicker(){const p=patients[selected];return `<div class="patient-switch"><div class="avatar">${p.initials}</div><div><label for="patient">SYNTHETIC PATIENT · ${p.age} YEARS</label><select id="patient" aria-label="Choose demo patient">${patients.map((p,i)=>`<option value="${i}" ${i===selected?'selected':''}>${p.name}</option>`).join('')}</select></div><span class="offline" title="Synthetic demo data"></span></div>`;}
function chart(p,kind='volume'){
 const isTrend=kind==='trend', data=isTrend?p.trend.map(t=>[t.week,t.fat]):p.samples.filter((r,i)=>i%5===0||r.voidFlag||(p.samples[i+1] && p.samples[i+1].voidFlag)).map(r=>[r.minute,r[kind]]);
 const maxX=isTrend?8:1440, minY=isTrend?Math.floor(Math.min(...data.map(d=>d[1]))-2):0;
 const maxY=isTrend?Math.ceil(Math.max(...data.map(d=>d[1]))+2):kind==='volume'?Math.ceil(Math.max(p.capacity,...data.map(d=>d[1]))/100)*100:100;
 const x=v=>32+v/maxX*292,y=v=>149-(v-minY)/(maxY-minY)*121;
 const path=data.map((d,i)=>`${i?'L':'M'}${x(d[0]).toFixed(2)},${y(d[1]).toFixed(2)}`).join(' ');
 const ticks=[minY,(minY+maxY)/2,maxY];
 return `<svg viewBox="0 0 340 184" role="img" aria-label="${isTrend?'Weekly regional impedance':kind==='volume'?'24-hour bladder volume':'24-hour '+kind} for ${p.name}"><defs><linearGradient id="fill" x1="0" y1="0" x2="0" y2="1"><stop stop-color="#bed396" stop-opacity=".45"/><stop offset="1" stop-color="#bed396" stop-opacity=".03"/></linearGradient></defs>${!isTrend?`<rect x="${x(p.sleepStart)}" y="20" width="${x(p.wake)-x(p.sleepStart)}" height="129" fill="#edf0e3" rx="4"/>`:''}${ticks.map(t=>`<line x1="32" y1="${y(t)}" x2="324" y2="${y(t)}" stroke="#edf0e7"/><text x="25" y="${y(t)+3}" text-anchor="end" fill="#8c9881" font-size="9">${Math.round(t)}</text>`).join('')}<path d="${path} L324,149 L32,149 Z" fill="url(#fill)"/><path d="${path}" stroke="#426d52" stroke-width="2" fill="none" stroke-linejoin="round"/>${isTrend?data.map(d=>`<circle cx="${x(d[0])}" cy="${y(d[1])}" r="3" fill="#426d52"/>`).join(''):p.events.map(e=>`<circle cx="${x(e.minute)}" cy="${y(kind==='volume'?e.post:p.samples[e.minute][kind])}" r="2.5" fill="#6f8d4f"/>`).join('')}${(isTrend?[0,2,4,6,8]:[0,360,720,1080,1440]).map(t=>`<text x="${x(t)}" y="174" text-anchor="middle" fill="#8c9881" font-size="9">${isTrend?'W'+t:clock(t)}</text>`).join('')}</svg>`;
}
function card(k,icon){const d=def(k),m=calculate(patients[selected]);return `<button class="metric-card" data-metric="${k}"><span class="icon">${icon}</span><span class="arrow">↗</span><div class="metric-value">${fmt(m[k],k)}<small>${d.unit}</small></div><div class="metric-label">${d.label}</div></button>`;}
function overview(p,m){return `<div class="intro"><div class="eyebrow">SEPTEMBER 8–9, 2026 · UTC</div><h1>Your daily rhythm.</h1><p class="sub">A clearer picture of bladder health.</p></div>${patientPicker()}
 <section class="hero" aria-label="Overnight summary"><div class="hero-top"><span class="eyebrow">THE NIGHT, AT A GLANCE</span><span class="moon">☾</span></div><div class="hero-body"><div><div class="hero-number">${fmt(m.nuv,'nuv')}<small>mL</small></div><p class="hero-label">Nocturnal urine volume</p></div><button class="ring" style="--pct:${m.npi}%" data-metric="npi" aria-label="Nocturnal polyuria index ${fmt(m.npi,'npi')} percent"><div><strong>${fmt(m.npi,'npi')}%</strong><small>of 24-hour output</small></div></button></div><div class="hero-footer"><span><b>${m.nightCount}</b> night void${m.nightCount===1?'':'s'}</span><span><b>${fmt(m.sleepHours,'sleepHours')}h</b> sleep window</span><span>22:00–05:30</span></div></section>
 <div class="section-head"><h2>The bigger picture</h2><button class="text-button" data-goto="biomarkers">All biomarkers ↗</button></div><div class="grid">${card('total','◒')}${card('mvv','⌁')}${card('efficiency','↙')}${card('heartRate','♡')}</div>
 <div class="insight"><span>✧</span><div><b>${p.profile}</b>${selected===0?'Two overnight voids contribute 550 mL; the first morning void adds 350 mL to NUV.':selected===1?'No nocturnal voids in this fixture. The 400 mL morning void still contributes to NUV.':'Twelve smaller voids and an 85 mL residual illustrate a different emptying pattern.'}</div></div>
 <div class="section-head"><h2>24 hours in flow</h2><button class="text-button" data-goto="timeline">Explore ↗</button></div><div class="chart-card"><div class="chart-head"><h3>Bladder volume</h3><span>mL · 1-min samples</span></div>${chart(p)}<div class="legend"><span><i></i>Stored volume</span><span><i class="sleep"></i>Sleep opportunity</span></div></div><p class="footnote">${p.id} · 1,441 samples · 24h coverage<br>Synthetic demo data. Sensor estimates are not clinical measurements.</p>`;}
function biomarkerRows(p,m){const ds=definitions.filter(d=>(group==='All'||d.group===group)&&`${d.label} ${d.status} ${d.detail}`.toLowerCase().includes(query.toLowerCase()));let last='';return ds.map(d=>{const head=d.group!==last?`<h3 class="group-title">${d.group}</h3>`:'';last=d.group;return `${head}<button class="metric-row" data-metric="${d.key}"><div><strong>${d.label}</strong><span class="status">${d.status}</span></div><div class="value">${fmt(m[d.key],d.key)}<small>${d.unit==='label'?'':d.unit}</small></div><span class="chevron">›</span></button>`;}).join('')||'<p class="empty">No matching biomarkers. Try another search.</p>';}
function biomarkers(p,m){return `<div class="intro"><div class="eyebrow">FROM SIGNAL TO INSIGHT</div><h1>Biomarkers.</h1><p class="sub">${definitions.length} measures. Every number has a story.</p></div>${patientPicker()}<input type="search" class="search" id="search" placeholder="Search biomarkers" aria-label="Search biomarkers" value="${esc(query)}"><div class="tabs" aria-label="Biomarker categories">${['All','Night','Filling','Voiding','Emptying','Symptoms','Context'].map(g=>`<button data-group="${g}" class="${g===group?'active':''}">${g}</button>`).join('')}</div><div id="metric-list">${biomarkerRows(p,m)}</div>`;}
const roleLabel={daytime:'Daytime void',pre_sleep:'Last pre-sleep void',nocturnal:'Nocturnal void',first_morning:'First morning void'};
function timeline(p,m){let events=p.events.filter(e=>timelineMode!=='Night'||e.nuv);return `<div class="intro"><div class="eyebrow">SEPTEMBER 8–9 · ALL TIMES UTC</div><h1>A day in detail.</h1><p class="sub">Follow the moments behind the measures.</p></div>${patientPicker()}<div class="chart-card"><div class="chart-head"><h3>Fill. Empty. Repeat.</h3><span>mL</span></div>${chart(p)}<div class="legend"><span><i></i>Bladder volume</span><span><i class="sleep"></i>Sleep window</span></div></div><div class="tabs">${['All','Night'].map(x=>`<button data-timeline="${x}" class="${timelineMode===x?'active':''}">${x==='All'?'All '+m.voidCount+' voids':'Night + morning'}</button>`).join('')}</div><div class="event-list">${events.map(e=>`<button class="event metric-row" data-event="${e.id}"><time>${clock(e.minute)}</time><div><strong>${roleLabel[e.role]}</strong><p>${e.minute>=1080?'Sep 9':'Sep 8'} · ${e.nuv?'Included in NUV':'Excluded from NUV'}</p></div><span class="event-value">${fmt(e.volume,'nuv')} <small>mL</small></span></button>`).join('')}</div><div class="data-note">The first morning void belongs to nocturnal urine volume, but is not counted as another nocturia episode.</div><div class="section-head"><h2>Diary moments</h2><span class="night-badge">Explicit mock inputs</span></div>${p.diary.length?p.diary.map(d=>`<div class="event"><time>${clock(d.minute)}</time><div><strong>${d.leak?'Urgency + leak':'Reported urgency'}</strong><p>${d.minute>=1080?'Sep 9':'Sep 8'} · Separate from the HRV urgency proxy</p></div></div>`).join(''):'<p class="sub">No urgency or leakage entries for this patient.</p>'}`;}
function trends(p,m){return `<div class="intro"><div class="eyebrow">CONTEXT OVER TIME</div><h1>The longer view.</h1><p class="sub">Explore eight weeks of synthetic signals.</p></div>${patientPicker()}<div class="chart-card"><div class="eyebrow">REGIONAL IMPEDANCE</div><div class="trend-stat"><strong>${fmt(Math.abs(m.fatTrend),'fatTrend')}%</strong><span>${m.fatTrend>=0?'decrease':'increase'} over 8 weeks</span></div><p class="sub">Sep 8 – Nov 3, 2026 · Z_fat in Ω</p>${chart(p,'trend')}</div><div class="data-note"><b>An impedance trend, not a fat-loss claim.</b><br>These weekly values are independent mock inputs. Impedance alone does not establish body-fat change or treatment response.</div><div class="grid">${card('conductance','⌁')}${card('hrv','♡')}</div><div class="section-head"><h2>Weekly readings</h2><span class="night-badge">Synthetic</span></div><div class="chart-card"><div class="trend-table"><span class="table-head">WEEK / DATE</span><span class="table-head">IMPEDANCE</span><span class="table-head">CONDUCTANCE</span>${p.trend.map(t=>`<span>W${t.week} · ${t.date.slice(5)}</span><span>${fmt(t.fat,'fat')} Ω</span><span>${fmt(1000/t.fat,'conductance')} mS</span>`).join('')}</div></div>`;}
function render(){const p=patients[selected],m=calculate(p);$('#main').innerHTML=({overview,biomarkers,timeline,trends})[tab](p,m);document.querySelectorAll('nav button').forEach(b=>{b.classList.toggle('active',b.dataset.tab===tab);b.setAttribute('aria-current',b.dataset.tab===tab?'page':'false');});}
function showSheet(content){$('#sheet-content').innerHTML=content;$('#sheet').showModal();}
function showMetric(k){const d=def(k),p=patients[selected],m=calculate(p);showSheet(`<div class="eyebrow">${d.group} · ${p.name}</div><h2>${d.label}</h2><div class="detail-value">${fmt(m[k],k)} <small>${d.unit==='label'?'':d.unit}</small></div><span class="tag">${d.status}</span><p>${d.detail}</p><div class="eyebrow">CALCULATION</div><code>${esc(d.formula)}</code><p class="sub">Source: ${p.id}. All observations and questionnaire responses in this app are synthetic.</p>`);}
document.addEventListener('click',ev=>{const b=ev.target.closest('button');if(!b)return;if(b.dataset.metric)showMetric(b.dataset.metric);if(b.dataset.tab||b.dataset.goto){tab=b.dataset.tab||b.dataset.goto;render();window.scrollTo(0,0);}if(b.dataset.group){group=b.dataset.group;render();}if(b.dataset.timeline){timelineMode=b.dataset.timeline;render();}if(b.dataset.event){const e=patients[selected].events.find(e=>e.id===b.dataset.event);showSheet(`<div class="eyebrow">${clock(e.minute)} UTC · ${e.id}</div><h2>${roleLabel[e.role]}</h2><div class="detail-value">${fmt(e.volume,'nuv')} <small>mL</small></div><span class="tag">${e.nuv?'Included in NUV':'Excluded from NUV'}</span><p>Pre-void ${fmt(e.pre,'nuv')} mL → post-void ${fmt(e.post,'nuv')} mL.</p><code>${fmt(e.pre,'nuv')} − ${fmt(e.post,'nuv')} = ${fmt(e.volume,'nuv')} mL</code><p>Mock stopwatch duration: ${e.durationSeconds} seconds. This timing is an additional synthetic input; one-minute sampling cannot measure it.</p>`);}});
document.addEventListener('change',ev=>{if(ev.target.id==='patient'){selected=Number(ev.target.value);render();}});
document.addEventListener('input',ev=>{if(ev.target.id==='search'){query=ev.target.value;$('#metric-list').innerHTML=biomarkerRows(patients[selected],calculate(patients[selected]));}});
$('#close-sheet').onclick=()=>$('#sheet').close();$('#sheet').addEventListener('click',ev=>{if(ev.target===$('#sheet')){const r=$('#sheet').getBoundingClientRect();if(ev.clientY<r.top||ev.clientY>r.bottom||ev.clientX<r.left||ev.clientX>r.right)$('#sheet').close();}});
$('#brand').onclick=ev=>{ev.preventDefault();tab='overview';render();window.scrollTo(0,0);};
$('#about').onclick=()=>showSheet('<div class="eyebrow">MIFLOW · OFFLINE DEMO</div><h2>A little more clarity.</h2><p>Three fictional patients. One complete day each. All demo data, charts and calculations are included with the app. Wait for Ready offline before using it without internet.</p><ul><li>No login, analytics or data uploads. An initial download saves this synthetic demo for offline use; reconnecting can check for app updates.</li><li>September 8–9, 2026; times are explicitly UTC.</li><li>Weekly impedance inputs extend through November 3.</li><li>Experimental proxies are labeled. No diagnosis or treatment advice is provided.</li><li>Qmax is unavailable without a high-rate flow trace.</li><li>IPSS values are two mock questionnaire domains, not total IPSS.</li></ul><p>Based on the supplied MiFlow biomarker workbook, with corrected event, residual and questionnaire definitions. Reopening starts with the original demo patient.</p>');
render();
